# POST http://localhost:3000/cart
# Content-Type: application/json

# {
#     "userId" : "checkinglogin@gmail.com",
#     "products": [{
#         "product" : "PRD1",
#         "quantity": 4
#     }]
    
# }

# POST http://localhost:3000/wishlist
# Content-Type: application/json

# {
#     "userId" : "checkinglogin@gmail.com",
#     "products": ["PRD2"]
    
# }

# GET  http://localhost:3000/cart/checkinglogin@gmail.com
# Content-Type: application/json


# DELETE http://localhost:3000/cart/checkinglogin@gmail.com/PRD1
# Content-Type: application/json

# PATCH http://localhost:3000/cart/checkinglogin@gmail.com/PRD2
# Content-Type: application/json

PATCH http://localhost:3000/wishlist/checkinglogin@gmail.com/PRD1
Content-Type: application/json