GET http://localhost:3000/friends/conversation/69521fbdce4b6c6ef813de1e


# GET http://localhost:3000/friends/requests
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTUyMWJiYTBkZDg0NjQ3OGU2ZTYzM2IiLCJlbWFpbCI6InVzZXJiQHRlc3QuY29tIiwiaWF0IjoxNzY2OTg4OTUxLCJleHAiOjE3NjcwNzUzNTF9.kLTTh_VMhAEAi8yVvnwc05GWJU2VzomHvXTRVyrcRyg

# POST http://localhost:3000/friends/connect
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTUyMWJjOTBkZDg0NjQ3OGU2ZTYzM2UiLCJlbWFpbCI6InVzZXJhQHRlc3QuY29tIiwiaWF0IjoxNzY2OTg4Nzg5LCJleHAiOjE3NjcwNzUxODl9.ckkJr1hzTXFTx5NIajwGilbbP_pDg8g46I9BJmqOToU
# Content-Type: application/json

# {
#   "friendCode": "68E5F6"
# }

# POST http://localhost:3000/friends/accept
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTUyMWIxMTBkZDg0NjQ3OGU2ZTYzMzgiLCJlbWFpbCI6InVzZXJjQHRlc3QuY29tIiwiaWF0IjoxNzY2OTg5NzE0LCJleHAiOjE3NjcwNzYxMTR9.VzuSkMrAciAIpeVVQ7HpjA8nCXQIekyzr4S3dpN5tBQ
# Content-Type: application/json

# {
#   "requestId": "69521c6a0dd846478e6e634a"
# }

# GET http://localhost:3000/friends/conversationIds
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTUyMWJiYTBkZDg0NjQ3OGU2ZTYzM2IiLCJlbWFpbCI6InVzZXJiQHRlc3QuY29tIiwiaWF0IjoxNzY2OTg4OTUxLCJleHAiOjE3NjcwNzUzNTF9.kLTTh_VMhAEAi8yVvnwc05GWJU2VzomHvXTRVyrcRyg

# POST http://localhost:3000/login
# Content-Type: application/json

# {
#   "email": "userC@test.com",
#   "password": "password12"
# }

# POST http://localhost:3000/registration
# Content-Type: application/json

# {
#   "userName": "userA",
#   "email": "userA@test.com",
#   "password": "password123"
# }

# AI query:
# POST http://localhost:3000/ask
# Content-Type: application/json

# {
#     "query" : "where are my orders"
# }

# GET http://localhost:3000/getaddress/shiro@gmail.com
# Content-Type: application/json

#update status:
# PUT http://localhost:3000/updatestatus/ORDID174130
# Content-Type: application/json

# {
#     "status": "transit"
# }

#update address:
# POST http://localhost:3000/updateaddress
# Content-Type: application/json

# {
#      "email" : "krithiperu2002@gmail.com",
#      "shippingAddress": {
#      "name": "Krithiga Perumal",
#      "address": "123 Main St",
#      "city": "Anytown",
#      "state": "TN",
#      "zip": "12345",
#      "country": "India"
#    }
 
# }

# GET http://localhost:3000/orders/krithiperu2002@gmail.com
# Content-Type: application/json

# POST http://localhost:3000/createOrder
# Content-Type: application/json

# {
#     "email" : "krithiperu2002@gmail.com",
#     "orderId": "ORDID0000788",
#      "products": [
#     {
#       "product": "PRD17",
#       "quantity": 1,
#       "price": 199
#     }
   
#   ],
#   "subtotal": 198,
#   "tax": 40,
#   "total": 238,
#   "paymentMethod": "credit card",
#   "paymentStatus": "paid",
#   "orderStatus": "processing",
#   "shippingAddress": {
#   "name": "Krithiga Perumal",
#   "address": "123 Main St",
#   "city": "Anytown",
#   "state": "TN",
#   "zip": "12345",
#   "country": "India"
# }
# }

#DELETE http://localhost:3000/clearcart/checkinglogin@gmail.com
# Content-Type: application/json

# POST http://localhost:3000/cart
# Content-Type: application/json

# {
#     "userId" : "krithiperu2002@gmail.com",
#     "products": [{
#         "product" : "PRD15",
#         "quantity": 1,
# 		"size": "S"
#     }]
    
# }

# POST http://localhost:3000/wishlist
# Content-Type: application/json

# {
#     "userId" : "checkinglogin@gmail.com",
#     "products": ["PRD2"]
    
# }

# GET  http://localhost:3000/cart/checkinglogin@gmail.com
# Content-Type: application/json


# DELETE http://localhost:3000/cart/checkinglogin@gmail.com/PRD1
# Content-Type: application/json

# PATCH http://localhost:3000/cart/checkinglogin@gmail.com/PRD2
# Content-Type: application/json

# PATCH http://localhost:3000/wishlist/checkinglogin@gmail.com/PRD1
# Content-Type: application/json

# DELETE http://localhost:3000/wishlist/checkinglogin@gmail.com/PRD2
# Content-Type: application/json

# # #payment:
# POST http://localhost:3000/createpayment
# Content-Type: application/json

# {
#     "email" : "newcustomer@gmail.com",
#     "name" : "newcustomer",
#     "amount" : 100
# }

# # add to cart
# POST http://localhost:3000/addproduct
# Content-Type: application/json

# {
# 	    "id": "PRD20",
# 	    "productName":   "Classic White High-Top Sneakers",
# 	    "price": 1199,
# 	    "description": "Inspired by the timeless Converse design, perfect for casual wear, street style, or athletics.",
# 	    "image": "https://hhatffzhvdmybvizyvhw.supabase.co/storage/v1/object/public/flut-images/footwear/high_top.jpg",
# 	    "rating": 5,
# 	    "category": "footwear"
# }



#get products
# GET http://localhost:3000/products
# Content-Type: application/json


# GET http://localhost:3000/search/shirt
# Content-Type: application/json

# {
#     "searchQuery" : "shirt"
# }


# #get category:
# GET http://localhost:3000/category/clothes
# Content-Type: application/json


#new payment
# POST http://localhost:3000/newpayment
# Content-Type: application/json

# {
#         "email": "newcustomer@gmail.com",
#         "name":  "newcustomer",
#         "amount" : 100,
#         "cardNumber": "424242424242",
#         "expMonth" : 12,
#         "expYear" : 2027,
#         "cvc": "123"
# }